# Generated by Django 5.2.6 on 2025-10-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_user_address_user_city_user_country_user_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(default='', max_length=150),
        ),
    ]
